import {z} from 'zod';
export const domains=['Conflict','Aviation','Connectivity','Earth observation','Maritime','Media & diplomacy','Social','Financial markets'] as const;
export const geographies=['Global','Ukraine','Pakistan','Uzbekistan','Kazakhstan','Bangladesh'] as const;
export const lifecycles=['Open','Monitoring','Mitigating','Resolved','Archived'] as const;
export const sourceSeeds=[
 ['acled','ACLED Core / CAST / Conflict Index','Conflict'],['ucdp','UCDP','Conflict'],['gdacs','GDACS','Conflict'],['gpsjam','GPSJAM','Aviation'],['adsb','ADS-B Exchange','Aviation'],['flightradar','Flightradar24','Aviation'],['safeairspace','Safe Airspace','Aviation'],['easa','EASA CZIB','Aviation'],['ioda','IODA','Connectivity'],['cloudflare','Cloudflare Radar','Connectivity'],['netblocks','NetBlocks','Connectivity'],['firms','NASA FIRMS','Earth observation'],['copernicus','Copernicus Sentinel','Earth observation'],['portwatch','IMF PortWatch','Maritime'],['fishingwatch','Global Fishing Watch','Maritime'],['gdelt','GDELT','Media & diplomacy'],['crisiswatch','CrisisWatch','Media & diplomacy'],['x','X public content','Social'],['meta','Meta public content','Social'],['telegram','Telegram public channels','Social'],['discord','Authorized Discord servers','Social'],['marketdata','Licensed FX / futures provider','Financial markets'],['officialfx','Official reference rates','Financial markets']
].map(([id,name,domain])=>({id,name,domain,owner:'',license:'',cadence:'Not configured',coverage:'',lineage:'',contact:'',retention:'Pending rights review',status:'Unavailable',lastSuccess:null}));
export type Instrument={id:string;name:string;family:'FX spot'|'Currency futures'|'Oil futures'|'Gold futures'|'Local derivatives';unit:string;exchange:string;market:string;threshold:number;five:number|null;direction:'up'|'absolute'};
export const instruments:Instrument[]=[...['UAH','PKR','UZS','KZT','BDT'].map((c,i)=>({id:'USD'+c,name:'USD / '+c,family:'FX spot' as const,unit:c+' per USD',exchange:'OTC / reference',market:geographies[i+1],threshold:2,five:5,direction:'up' as const})),{id:'EURUSD',name:'EUR / USD',family:'FX spot',unit:'USD per EUR',exchange:'OTC',market:'Global',threshold:2,five:5,direction:'absolute'},...(['front','3M','6M'] as const).flatMap(tenor=>[
 {id:'6E-'+tenor,name:'Euro FX · '+tenor,family:'Currency futures' as const,unit:'USD per EUR',exchange:'CME',market:'Global',threshold:1.5,five:null,direction:'absolute' as const},
 {id:'BRENT-'+tenor,name:'Brent · '+tenor,family:'Oil futures' as const,unit:'USD / barrel',exchange:'ICE',market:'Global',threshold:5,five:10,direction:'absolute' as const},
 {id:'CL-'+tenor,name:'WTI · '+tenor,family:'Oil futures' as const,unit:'USD / barrel',exchange:'NYMEX',market:'Global',threshold:5,five:10,direction:'absolute' as const},
 {id:'GC-'+tenor,name:'Gold · '+tenor,family:'Gold futures' as const,unit:'USD / troy oz',exchange:'COMEX',market:'Global',threshold:3,five:6,direction:'absolute' as const}]),...['UAH','PKR','UZS','KZT','BDT'].map((c,i)=>({id:c+'-DERIV',name:c+' forwards / NDFs',family:'Local derivatives' as const,unit:'Contract-dependent',exchange:'Coverage to verify',market:geographies[i+1],threshold:2,five:5,direction:'up' as const}))];
const score=z.number().min(0).max(100).nullable();
export const assessmentSchema=z.object({situationId:z.string().min(1).max(100),lifecycle:z.enum(lifecycles),reviewDue:z.string().max(40),linkReason:z.string().max(3000),rationale:z.string().min(3).max(5000),severity:score,plausibility:z.union([z.literal(0),z.literal(25),z.literal(50),z.literal(75),z.literal(100),z.null()]),business:score,velocity:score,reliability:score,corroboration:score,quality:score,precision:score,impacts:z.object({people:z.string(),network:z.string(),regulation:z.string(),finance:z.string(),supplyChain:z.string(),reputation:z.string()}),playbook:z.string().max(5000),owner:z.string().max(200),revision:z.number().int().min(0).default(0)});
export type Assessment=z.infer<typeof assessmentSchema>;
export function blankAssessment(situationId:string):Assessment{return {situationId,lifecycle:'Open',reviewDue:'',linkReason:'',rationale:'',severity:null,plausibility:null,business:null,velocity:null,reliability:null,corroboration:null,quality:null,precision:null,impacts:{people:'Unknown',network:'Unknown',regulation:'Unknown',finance:'Unknown',supplyChain:'Unknown',reputation:'Unknown'},playbook:'',owner:'',revision:0}}
export const evidenceSchema=z.object({id:z.string().max(100),situationId:z.string().min(1).max(100),title:z.string().min(3).max(300),sourceId:z.string().min(1).max(100),domain:z.enum(domains),lineage:z.string().min(2).max(200),geography:z.enum(geographies),observedAt:z.string().datetime(),publishedAt:z.string().datetime(),url:z.string().url().refine(x=>/^https?:/.test(x)),stance:z.enum(['Supports','Contradicts','Context']),verified:z.boolean(),exposureApproved:z.boolean(),exposureReason:z.string().max(3000),notes:z.string().max(4000),synthetic:z.boolean()});
export type Evidence=z.infer<typeof evidenceSchema>&{receivedAt:string};
export const quoteSchema=z.object({eventId:z.string().min(1).max(180),instrumentId:z.string().refine(x=>instruments.some(i=>i.id===x)),value:z.number().finite(),previous:z.number().finite().nullable(),fiveSessions:z.number().finite().nullable(),hourAgo:z.number().finite().nullable().default(null),unit:z.string().min(1).max(60),source:z.string().min(2).max(180),observedAt:z.string().datetime(),publishedAt:z.string().datetime(),session:z.enum(['Open','Closed']),kind:z.enum(['Intraday','Delayed','Reference']),delayMinutes:z.number().min(0).max(1440),contract:z.string().max(100),comparisonContract:z.string().max(100),expiry:z.string().max(40),rollOn:z.string().max(40),volume:z.number().nonnegative().nullable(),openInterest:z.number().nonnegative().nullable(),nextExpectedAt:z.string().datetime().nullable(),synthetic:z.boolean().default(false)});
export type Quote=z.infer<typeof quoteSchema>&{receivedAt:string;origin:'import'|'connector'};
export type Alert={id:string;situationId:string;title:string;state:'Candidate'|'Under review'|'Approved'|'Acknowledged'|'Action recorded'|'Closed';kind:'Geopolitical'|'Economic';score:number|null;tier:string;confidence:number|null;createdAt:string;updatedAt:string;assessmentRevision:number;evidenceIds:string[];rationale:string;override:boolean;overrideReason:string;approvedBy?:string;approvedAt?:string;acknowledgedAt?:string;decision?:string;outcome?:string;instrumentId?:string};
export type Audit={id:string;kind:string;entityId:string;actor:string;at:string;data:Record<string,unknown>};
export type Source=Omit<typeof sourceSeeds[number],'lastSuccess'> & {lastSuccess:string|null};
export type Brief={id:string;type:'Daily'|'Weekly';createdAt:string;state:'Draft'|'Approved';approvedAt?:string;approvedBy?:string;scope:string;content:string};
export type MarketCandidate={id:string;instrumentId:string;createdAt:string;quote:Quote;rule:string;state:string;message:string};
export type Workspace={marketCandidates:MarketCandidate[];assessments:Assessment[];evidence:Evidence[];alerts:Alert[];sources:Source[];quotes:Quote[];audit:Audit[];briefs:Brief[];preferences:{moon:boolean;timezone:string};connector:{configured:boolean;lastRun:string|null;error:string|null};};
