import {env} from '@/lib/horizon/env';
import {z} from 'zod';

export const dynamic = 'force-dynamic';
import {actor,mutationGuard} from '@/lib/horizon/auth';
import {quoteSchema,instruments,sourceSeeds,type Source,type Quote} from '@/lib/horizon/model';
import {readRecord,writeRecord,records} from '@/lib/horizon/storage';
import {marketCondition} from '@/lib/horizon/engine';
export async function POST(request:Request){try{mutationGuard(request);const who=actor(request),config=env as unknown as Record<string,string>;if(!config.MARKET_FEED_URL)return Response.json({error:'No market provider connected. A licensed normalized feed and server credentials are required.'},{status:503});const url=new URL(config.MARKET_FEED_URL);if(url.protocol!=='https:')throw Error('Provider must use HTTPS');const oldStatus=await readRecord<{lastRun:string}>('connector:status');if(oldStatus&&Date.now()-Date.parse(oldStatus.data.lastRun)<55000)throw Error('Wait 60 seconds between provider requests');const at=new Date().toISOString();await writeRecord('connector:status','connector',{lastRun:at,error:null},who,oldStatus?.version||null,'Provider sync started');
 try{const response=await fetch(url,{headers:config.MARKET_FEED_TOKEN?{Authorization:'Bearer '+config.MARKET_FEED_TOKEN}:{},redirect:'error',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Provider returned HTTP '+response.status);const raw=await response.text();if(raw.length>1000000)throw Error('Provider payload too large');const data=z.array(quoteSchema).max(500).parse(JSON.parse(raw));let imported=0;
 for(const q of data){const i=instruments.find(i=>i.id===q.instrumentId)!;if(q.unit!==i.unit)throw Error('Provider unit mismatch: '+i.id);if(Date.parse(q.observedAt)>Date.now()+60000||Date.parse(q.publishedAt)>Date.now()+60000)throw Error('Future provider timestamp');if(i.family.includes('futures')&&(!q.contract||!q.expiry||!q.rollOn))throw Error('Missing verified contract metadata');const id='quote:'+q.source+':'+q.eventId;const existing=await readRecord<Quote>(id);const quote:Quote=existing?.data||{...q,origin:'connector',receivedAt:new Date().toISOString()};if(!existing){await writeRecord(id,'quote',quote,'Provider',null,'Quote ingested');imported++;}
 // Evaluate only distinct, chronological live observations. Imported/synthetic data never notify.
 const stateId='market-rule:'+q.instrumentId,old=await readRecord<any>(stateId),previous=old?.data;
 if(previous&&Date.parse(q.observedAt)<=Date.parse(previous.observedAt))continue;
 const condition=marketCondition(quote),sameContract=previous?.contract===q.contract,sameDirection=previous?.direction===condition.direction;
 const hits=condition.eligible&&condition.hit?(sameContract&&sameDirection?(previous?.hits||0)+1:1):0;
 const clear=condition.eligible&&condition.clear?(previous?.clear||0)+1:0;
 const state={observedAt:q.observedAt,contract:q.contract,direction:condition.direction,hits,clear,lastAlert:previous?.lastAlert||null,active:clear>=3?false:previous?.active||false};
 if(hits>=2&&!state.active&&(!state.lastAlert||Date.now()-Date.parse(state.lastAlert)>=4*3600000)){const cid=q.instrumentId+':'+q.source+':'+q.eventId;if(!await readRecord('market-candidate:'+cid))await writeRecord('market-candidate:'+cid,'market-candidate',{id:cid,instrumentId:q.instrumentId,createdAt:at,quote,rule:'pilot-v1',state:'Treasury review required',message:'Two fresh evaluations crossed the proposed threshold. Exposure review required.'},'Rule engine',null,'Economic candidate');state.lastAlert=at;state.active=true;}
 await writeRecord(stateId,'market-rule',state,'Rule engine',old?.version||null,'Market rule evaluation');}
 const registry=await readRecord<Source>('source:marketdata');await writeRecord('source:marketdata','source',{...(registry?.data||sourceSeeds.find(s=>s.id==='marketdata')),status:'Connected',lastSuccess:at},'Provider',registry?.version||null,'Source health');const latest=await readRecord('connector:status');await writeRecord('connector:status','connector',{lastRun:at,error:null},who,latest!.version,'Provider sync complete');return Response.json({ok:true,imported});}catch(e){const latest=await readRecord('connector:status');await writeRecord('connector:status','connector',{lastRun:at,error:(e as Error).message},who,latest!.version,'Provider sync failed');throw e;}
 }catch(e){return Response.json({error:(e as Error).message},{status:(e as Error).message==='Access denied'?403:400})}}
