import { z } from 'zod';
export const markets=['Ukraine','Pakistan','Uzbekistan','Kazakhstan','Bangladesh'] as const;
const scenario=z.object({severity:z.number().int().min(1).max(3),duration:z.number().int().min(1).max(3),description:z.string().max(2500),trigger:z.string().max(2500),action:z.string().max(2500),assumptions:z.string().max(2500).optional(),implications:z.string().max(2500).optional(),owner:z.string().max(200).optional(),reviewDue:z.string().max(40).optional(),supportingEvidence:z.string().max(2500).optional(),conflictingEvidence:z.string().max(2500).optional()});
export const situationSchema=z.object({id:z.string().max(100),title:z.string().min(3).max(180),scope:z.enum(['Global',...markets]),markets:z.array(z.enum(markets)),marketReasons:z.record(z.string().max(2500)).optional(),driver:z.enum(['Armed conflict','Technology controls','Trade & sanctions','Political & regulatory','Energy & infrastructure']),status:z.enum(['Monitor','Watch','Escalate','Resolved']),confidence:z.enum(['Low','Medium','High']),owner:z.string().max(120),summary:z.string().max(4000),exposure:z.string().max(3000),opportunity:z.string().max(2000),scenarios:z.object({Optimistic:scenario,Base:scenario,Pessimistic:scenario}),sources:z.array(z.object({title:z.string().max(300),url:z.string().max(2000).refine(v=>!v||/^https?:\/\//.test(v)),date:z.string().max(40)})).max(50),notes:z.array(z.object({text:z.string().max(4000),date:z.string().max(40)})).max(100),signals:z.array(z.object({name:z.string().max(100),value:z.number(),baseline:z.number(),threshold:z.number(),unit:z.string().max(30),date:z.string().max(40)})).max(30),illustrative:z.boolean(),updated:z.string().max(40)});
export type Situation=z.infer<typeof situationSchema>;
export type ScenarioName='Optimistic'|'Base'|'Pessimistic';
export function blankSituation():Situation{return {id:crypto.randomUUID(),title:'',scope:'Global',markets:[],driver:'Armed conflict',status:'Monitor',confidence:'Low',owner:'Corporate Affairs',summary:'',exposure:'',opportunity:'',scenarios:{Optimistic:{severity:1,duration:1,description:'',trigger:'',action:''},Base:{severity:2,duration:2,description:'',trigger:'',action:''},Pessimistic:{severity:3,duration:3,description:'',trigger:'',action:''}},sources:[],notes:[],signals:[],illustrative:false,updated:new Date().toISOString()};}
const definitions=[
['G01','Regional conflict & airspace disruption','Global','Armed conflict',3,2,'Escalate','Regional escalation could constrain air corridors and amplify energy and insurance costs.','People mobility, equipment logistics and backup power costs.','Investigate alternative logistics corridors and local supplier capacity.','Review travel exposure and continuity plans with market teams.'],
['G02','Technology supply chain fragmentation','Global','Technology controls',2,3,'Watch','Diverging technology rules could limit access to network equipment, cloud services and AI infrastructure.','Vendor concentration, procurement lead times and technology investment.','Evaluate diversified suppliers and compliant local infrastructure.','Map critical vendor dependencies and identify qualified alternatives.'],
['UA01','Energy infrastructure disruption','Ukraine','Energy & infrastructure',3,3,'Escalate','A prolonged infrastructure disruption scenario could constrain network power availability.','Network uptime, staff safety and access to backup energy.','Strengthen resilient connectivity services for enterprise customers.','Validate generator readiness, fuel buffers and critical-site priorities.'],
['PK01','Cross-border security escalation','Pakistan','Armed conflict',3,1,'Watch','A border escalation scenario could affect transport corridors and workforce movement.','Field teams, equipment delivery and service continuity near affected areas.','Assess alternate distribution routes and remote servicing.','Review travel triggers and alternate supply routes.'],
['UZ01','Digital regulation & investment conditions','Uzbekistan','Political & regulatory',2,2,'Monitor','Changes to digital-sector rules could alter investment timing and operating requirements.','Spectrum, data governance and capital allocation.','Engage on investment conditions and digital infrastructure partnerships.','Track official consultations and assess implementation dependencies.'],
['KZ01','Trade corridor & sanctions spillovers','Kazakhstan','Trade & sanctions',2,3,'Watch','Disrupted regional corridors could create compliance and equipment sourcing friction.','Cross-border payments, logistics and supplier due diligence.','Explore emerging trade corridors and enterprise demand.','Review corridor alternatives and screening requirements with Legal.'],
['BD01','Political transition & operating continuity','Bangladesh','Political & regulatory',2,1,'Watch','Political uncertainty could delay policy decisions or interrupt local operations.','Field operations, permits and commercial planning.','Build stakeholder understanding of digital inclusion priorities.','Validate local continuity arrangements and stakeholder engagement.']
] as const;
export const seed:Situation[]=definitions.map((d,i)=>({id:d[0],title:d[1],scope:d[2],markets:d[2]==='Global'?[...markets]:[d[2]],driver:d[3],status:d[6],confidence:'Low',owner:d[2]==='Global'?'Group Corporate Affairs':d[2]+' Corporate Affairs',summary:d[7],exposure:d[8],opportunity:d[9],scenarios:{Optimistic:{severity:1,duration:1,description:'Disruption remains localized and conditions normalize quickly.',trigger:'Restrictions ease and two independent indicators return to baseline.',action:'Maintain monitoring; evaluate the identified commercial opportunity.'},Base:{severity:d[4],duration:d[5],description:d[7],trigger:'Two independent signal families exceed their review thresholds.',action:d[10]},Pessimistic:{severity:3,duration:3,description:'Disruption broadens, persists and affects multiple operating dependencies.',trigger:'Official restrictions and sustained operational impacts confirm escalation.',action:'Activate the relevant continuity playbook and escalate resource decisions to leadership.'}},sources:[],notes:[],signals:[{name:'Aviation activity',value:20+i*3,baseline:10,threshold:25,unit:'diversions / week',date:'2026-09-15'},{name:'Insurance pricing',value:115+i*4,baseline:100,threshold:120,unit:'index',date:'2026-09-15'},{name:'Energy & futures',value:108+i*2,baseline:100,threshold:115,unit:'index',date:'2026-09-15'}],illustrative:true,updated:'2026-09-15T09:00:00Z'}));
