import {z} from 'zod';
import {env} from 'cloudflare:workers';
import {database} from '@/db/store';
import {actor,mutationGuard} from '@/lib/horizon/auth';
import {records,readRecord,writeRecord} from '@/lib/horizon/storage';
import {assessmentSchema,evidenceSchema,quoteSchema,sourceSeeds,type Assessment,type Evidence,type Alert,type Source,type Brief,type Quote,type MarketCandidate,instruments} from '@/lib/horizon/model';
import {clueGate,confidence,risk,tier} from '@/lib/horizon/engine';
import {seed,type Situation} from '@/lib/situations';
async function situation(id:string){const row=await database().prepare('SELECT data FROM situations WHERE id=?').bind(id).first<{data:string}>();const s=row?JSON.parse(row.data) as Situation:seed.find(s=>s.id===id);if(!s)throw Error('Situation not found');return s;}
function fail(e:unknown){const message=e instanceof z.ZodError?'Check required fields, dates and values.':(e as Error).message;return Response.json({error:message},{status:message==='Access denied'?403:message.startsWith('Conflict')?409:400});}
export async function GET(request:Request){try{const who=actor(request);const url=new URL(request.url);if(url.searchParams.has('history')){const id=url.searchParams.get('history')!;const result=await database().prepare('SELECT * FROM audit_events WHERE entity_id IN (?,?) ORDER BY at DESC LIMIT 100').bind(id,'assessment:'+id).all();return Response.json(result.results.map((x:any)=>({...x,entityId:x.entity_id,data:JSON.parse(x.data)})));}const [assessments,evidence,alerts,sources,quotes,briefs,marketCandidates,prefs,connector,log]=await Promise.all([records<Assessment>('assessment'),records<Evidence>('evidence'),records<Alert>('alert'),records<Source>('source'),records<Quote>('quote',3000),records<Brief>('brief',100),records<MarketCandidate>('market-candidate',100),readRecord<{moon:boolean;timezone:string}>('preference:'+who),readRecord<{lastRun:string;error:string|null}>('connector:status'),database().prepare('SELECT * FROM audit_events ORDER BY at DESC LIMIT 200').all()]);return Response.json({marketCandidates,assessments,evidence,alerts,sources:sourceSeeds.map(s=>sources.find(x=>x.id===s.id)||s),quotes,briefs,preferences:prefs?.data||{moon:false,timezone:'Asia/Dubai'},connector:{configured:!!(env as unknown as Record<string,string>).MARKET_FEED_URL,lastRun:connector?.data.lastRun||null,error:connector?.data.error||null},audit:log.results.map((x:any)=>({...x,entityId:x.entity_id,data:JSON.parse(x.data)}))});}catch(e){return fail(e)}}
export async function POST(request:Request){try{mutationGuard(request);const who=actor(request);if(Number(request.headers.get('content-length')||0)>1000000)throw Error('Payload too large');const body=z.object({action:z.string(),data:z.unknown().optional(),id:z.string().optional()}).parse(await request.json());const now=new Date().toISOString();
 if(body.action==='assessment'){const data=assessmentSchema.parse(body.data);await situation(data.situationId);const id='assessment:'+data.situationId;const old=await readRecord<Assessment>(id);if((old?.data.revision||0)!==data.revision)throw Error('Conflict: assessment changed. Reload before saving.');data.revision++;await writeRecord(id,'assessment',data,who,old?.version||null,'Assessment revision');}
 else if(body.action==='evidence'){const data=evidenceSchema.parse(body.data);await situation(data.situationId);if(!sourceSeeds.some(s=>s.id===data.sourceId&&s.domain===data.domain))throw Error('Source and evidence domain do not match');if(Date.parse(data.observedAt)>Date.now()||Date.parse(data.publishedAt)>Date.now())throw Error('Evidence timestamps cannot be in the future');const id='evidence:'+data.id;if(await readRecord(id))throw Error('Evidence is immutable. Add a new correction record.');await writeRecord(id,'evidence',{...data,receivedAt:now},who,null,'Evidence added');}
 else if(body.action==='preferences'){const data=z.object({moon:z.boolean(),timezone:z.string()}).parse(body.data);new Intl.DateTimeFormat('en',{timeZone:data.timezone});const id='preference:'+who,old=await readRecord(id);await writeRecord(id,'preference',data,who,old?.version||null,'Display preference');}
 else if(body.action==='source'){const data=z.object({id:z.string(),owner:z.string().max(200),license:z.string().max(3000),cadence:z.string().max(300),coverage:z.string().max(1000),lineage:z.string().max(300),contact:z.string().max(300),retention:z.string().max(300)}).parse(body.data);const original=sourceSeeds.find(s=>s.id===data.id);if(!original)throw Error('Unknown source');const id='source:'+data.id,old=await readRecord<Source>(id);await writeRecord(id,'source',{...original,...old?.data,...data},who,old?.version||null,'Source onboarding');}
 else if(body.action==='quotes'){const quotes=z.array(quoteSchema).min(1).max(500).parse(body.data);let count=0;for(const q of quotes){const i=instruments.find(i=>i.id===q.instrumentId)!;if(q.unit!==i.unit)throw Error('Quote unit does not match instrument '+i.id);if(Date.parse(q.observedAt)>Date.now()+60000||Date.parse(q.publishedAt)>Date.now()+60000)throw Error('Quote timestamps cannot be in the future');if(i.family.includes('futures')&&(!q.contract||!q.expiry||!q.rollOn))throw Error('Futures require contract, expiry and verified roll date');const id='quote:'+q.source+':'+q.eventId;if(await readRecord(id))continue;await writeRecord(id,'quote',{...q,receivedAt:now,origin:'import'},who,null,'Quote imported');count++;}return Response.json({ok:true,imported:count});}
 else if(body.action==='candidate'){const input=z.object({situationId:z.string(),rationale:z.string().min(3).max(5000)}).parse(body.data);const s=await situation(input.situationId),assessment=await readRecord<Assessment>('assessment:'+s.id);const a=assessment?.data;const score=a?risk(a):null;const alert:Alert={id:crypto.randomUUID(),situationId:s.id,title:s.title,state:'Candidate',kind:'Geopolitical',score,tier:tier(score),confidence:a?confidence(a):null,createdAt:now,updatedAt:now,assessmentRevision:a?.revision||0,evidenceIds:[],rationale:input.rationale,override:false,overrideReason:''};await writeRecord('alert:'+alert.id,'alert',alert,who,null,'Candidate opened');}
 else if(body.action==='alert'){const input=z.object({id:z.string(),expectedAt:z.string(),state:z.enum(['Under review','Approved','Acknowledged','Action recorded','Closed']),reason:z.string().max(5000),override:z.boolean().default(false)}).parse(body.data);const id='alert:'+input.id,old=await readRecord<Alert>(id);if(!old)throw Error('Alert not found');const a=old.data;if(a.updatedAt!==input.expectedAt)throw Error('Conflict: alert changed. Reload before continuing.');const allowed:Record<string,string[]>={Candidate:['Under review','Closed'],'Under review':['Approved','Closed'],Approved:['Acknowledged','Closed'],Acknowledged:['Action recorded','Closed'],'Action recorded':['Closed'],Closed:[]};if(!allowed[a.state].includes(input.state))throw Error('Invalid alert transition');if(!input.reason.trim())throw Error('A review or decision rationale is required');
 if(input.state==='Approved'){const assessment=await readRecord<Assessment>('assessment:'+a.situationId);const s=await situation(a.situationId);if(s.illustrative)throw Error('Illustrative situations cannot be approved for operational use');if(!assessment)throw Error('Complete the situation assessment first');const score=risk(assessment.data),c=confidence(assessment.data);if(score===null||c===null)throw Error('Incomplete assessment');const evidence=await records<Evidence>('evidence');const gate=clueGate(evidence,s.id,s.scope,now);if(score>40&&(!gate.passed||c<50)&&!input.override)throw Error('Warning and above require three independent domains within 48 hours and confidence ≥ 50. Use a documented emergency override only for a confirmed emergency.');if(input.override&&input.reason.trim().length<30)throw Error('Emergency override requires a detailed rationale (at least 30 characters)');Object.assign(a,{score,tier:tier(score),confidence:c,assessmentRevision:assessment.data.revision,evidenceIds:gate.clues.map(e=>e.id),override:input.override,overrideReason:input.override?input.reason:'',approvedBy:who,approvedAt:now});}
 if(input.state==='Acknowledged')a.acknowledgedAt=now;if(input.state==='Action recorded')a.decision=input.reason;if(input.state==='Closed')a.outcome=input.reason;a.state=input.state;a.updatedAt=now;a.rationale=input.reason;await writeRecord(id,'alert',a,who,old.version,'Alert '+input.state);}
 else if(body.action==='brief'){const input=z.object({type:z.enum(['Daily','Weekly']),scope:z.string(),content:z.string().min(10).max(50000)}).parse(body.data);const data:Brief={id:crypto.randomUUID(),...input,createdAt:now,state:'Draft'};await writeRecord('brief:'+data.id,'brief',data,who,null,'Brief drafted');}
 else if(body.action==='approveBrief'){const id='brief:'+z.string().parse(body.id),old=await readRecord<Brief>(id);if(!old)throw Error('Brief not found');if(old.data.state!=='Draft')throw Error('Brief already approved');await writeRecord(id,'brief',{...old.data,state:'Approved',approvedAt:now,approvedBy:who},who,old.version,'Brief approved');}
 else if(body.action==='marketCandidateReview'){const input=z.object({id:z.string(),state:z.enum(['Reviewed','Dismissed']),reason:z.string().min(3).max(4000)}).parse(body.data);const id='market-candidate:'+input.id,old=await readRecord<MarketCandidate>(id);if(!old)throw Error('Market candidate not found');await writeRecord(id,'market-candidate',{...old.data,state:input.state,message:input.reason,reviewedAt:now,reviewer:who},who,old.version,'Treasury review recorded');}
 else if(body.action==='feedback'){const data=z.object({situationId:z.string(),text:z.string().min(3).max(5000),outcome:z.enum(['Confirmed','Dismissed','Needs review'])}).parse(body.data);await situation(data.situationId);await writeRecord('feedback:'+crypto.randomUUID(),'feedback',{...data,createdAt:now,state:'Pending review'},who,null,'Feedback recorded');}
 else throw Error('Unknown action');return Response.json({ok:true});
 }catch(e){return fail(e)}}
